### ISSUE TITLE
Taint failure in t/create.t

### ISSUE THREAD

**Issue by eserte** [rjbs/Email-ARF#2]
t/create.t recently started to fail:

```
Insecure $ENV{PATH} while running with -T switch at /usr/perl5.20.0/lib/site_perl/5.20.0/Sys/Hostname/Long.pm line 30.
# Looks like you planned 7 tests but ran 1.
# Looks like your test exited with 255 just after 1.
t/create.t .................... 
Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 6/7 subtests 
```

**Comment by rjbs** [comment]
How odd.  I've removed the -T, since I don't actually use taint mode and have never really tried using this module in production with it.  It'll be gone in the next release.

**Comment by eserte** [comment]
I think this change in a dependent module caused the problem: https://metacpan.org/source/RJBS/Email-MessageID-1.406/Changes#L3
It seems to be more likely that `Sys::Hostname::Long` is causing taint problems than `Sys::Hostname` --- the former always calls `hostname` with the current `$ENV{PATH}`, while the latter tries an XS function first (on linux/freebsd at least).

**Comment by eserte** [comment]
A known issue in Sys::Hostname::Long: https://rt.cpan.org/Ticket/Display.html?id=59833

**Comment by rjbs** [comment]
Thanks, interesting to know!
